- name: fetch list of namespaces
  k8s_info:
    kind: Namespace
  register: projects

- name: deploy cleaning cronjob
  k8s:
    namespace: "{{ lookup('env','WATCH_NAMESPACE') }}"
    merge_type: merge
    definition: "{{lookup('template', 'cleaning-cronjob.yaml')}}"
      apiVersion: batch/v1beta1
      kind: CronJob
      metadata:
        name: cleaning-cronjob-{{ item.metadata.name }}
      spec:
        schedule: "*/{{ garbageCollectorFrequency }} * * * *"
        concurrencyPolicy: "Replace"
        startingDeadlineSeconds: 200
        suspend: true
        successfulJobsHistoryLimit: 3
        failedJobsHistoryLimit: 1
        jobTemplate:
          spec:
            template:
              metadata:
                labels:
                  parent: "cleaning-jobs"
              spec:
                serviceAccount: cleaning-operator
                serviceAccountName: cleaning-operator
                containers:
                # TODO use image with openshift cli and write deletion script
                - name: busybox
                  image: busybox
                  command:
                    - "sleep"
                  args:
                    - "10"
                restartPolicy: OnFailure
    state: present
  loop: "{{ projects.resources }}"
