- name: fetch list of namespaces
  k8s_info:
    kind: Namespace
  register: projects

- name: create cleaning configmap
  k8s:
    namespace: "{{ lookup('env','WATCH_NAMESPACE') }}"
    merge_type: merge
    definition: "{{lookup('template', 'cronjob_configmap.yaml')}}"

- name: deploy cleaning cronjob
  k8s:
    namespace: "{{ lookup('env','WATCH_NAMESPACE') }}"
    merge_type: merge
    definition: "{{lookup('template', 'cleaning-cronjob.yaml')}}"
      apiVersion: batch/v1beta1
      kind: CronJob
      metadata:
        name: cleaner
      spec:
        schedule: "*/{{ garbageCollectorFrequency }} * * * *"
        concurrencyPolicy: "Replace"
        startingDeadlineSeconds: 200
        suspend: true
        successfulJobsHistoryLimit: 3
        failedJobsHistoryLimit: 1
        jobTemplate:
          spec:
            template:
              metadata:
                labels:
                  parent: "cleaning-jobs"
              spec:
                serviceAccount: cleaning-operator
                serviceAccountName: cleaning-operator
                containers:
                - name: cleaner
                  image: quay.io/operator-framework/ansible-operator:v0.18.0
                  command:
                    - "/usr/local/bin/ansible-playbook /srv/mount/playbook.yaml"
                  volumeMounts:
                  - name: test
                    mountPath: /srv/mount
                restartPolicy: OnFailure
                volumes:
                  - name: test
                    configMap:
                      name: cleaner-playbook
    state: present
