apiVersion: cleaning.ansible-operator.com/v1
kind: CleaningConfig
metadata:
  name: example-cleaningconfig
spec:
  protectedByDefault: true
  defaultExpiry: 10d
  garbageCollectorFrequency: 30m
status: {}
