# we don't want to build an image for CronJob
# put ansible code in configmap and mount it to cronjob pod
apiVersion: v1
kind: ConfigMap
metadata:
  name: ephemeralnamespace-cleaner-playbook
data:
  playbook.yaml: |
    - hosts: localhost
      tasks:
      - name: delete ephemeral namespace
        k8s:
          state: absent
          definition:
            kind: EphemeralNamespace
            apiVersion: v1
            metadata:
              name: "{{ '{{' }} eph_namespace {{ '}}' }}"
      - name: delete associated cleaning cronjob
        k8s:
          state: absent
          namespace: "{{ '{{' }} lookup('env','WATCH_NAMESPACE') {{ '}}' }}"
          definition:
            apiVersion: batch/v1beta1
            kind: CronJob
            metadata:
              name: "{{ '{{' }} eph_namespace {{ '}}' }}-cleaner"
