apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: default-params-cronjob
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: "Replace"
  startingDeadlineSeconds: 200
  suspend: true
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            parent: "default-params-jobs"
        spec:
          containers:
          - name: busybox
            image: busybox
            command:
              - sleep
            args:
              - 10
          restartPolicy: OnFailure
