---

- name: fetch ephemeral namespaces
  k8s_info:
    api_version: cleaning.ansible-operator.com/v1
    kind: EphemeralNamespace
    namespace: "{{ lookup('env','WATCH_NAMESPACE') }}"
  register: ephemeral_namespaces

- name: fetch namespaces
  k8s_info:
    kind: namespace
    namespace: "{{ lookup('env','WATCH_NAMESPACE') }}"
    label_selectors:
      - "cleaningOperator_ephemeralnamespace = true"
  register: namespaces

- name: fetch cronjobs
  k8s_info:
    api_version: batch/v1beta1
    kind: cronjobs
    namespace: "{{ lookup('env','WATCH_NAMESPACE') }}"
    label_selectors:
      - "cronjob-name = ephemeralnamespace-cleaning-jobs"
  register: cronjobs

# new ephemeral_namespace created => create associated namespace and cronjob
- name: create namespace associated to ephemeralnamespace
  import_tasks: configure_ephemeral_namespace.yaml
  when: namespaces.resources|length < ephemeral_namespaces.resources|length or
        cronjobs.resources|length < ephemeral_namespaces.resources|length
